#!/bin/sh                                                                                       

PID="org.webosinternals.govnah"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the govnah executable
rm -f /var/usr/sbin/${PID}

# Remove the dbus service
rm -f /usr/share/dbus-1/system-services/${PID}.service /var/palm/system-services/${PID}.service

# Remove the ls2 roles
rm -f /usr/share/ls2/roles/prv/${PID}.json /var/palm/ls2/roles/prv/${PID}.json
rm -f /usr/share/ls2/roles/pub/${PID}.json /var/palm/ls2/roles/pub/${PID}.json

# Stop the service if running
/sbin/stop ${PID} || true
/usr/bin/killall -9 ${PID} || true

# Remove the upstart script
rm -f /etc/event.d/${PID} /var/palm/event.d/${PID} /var/palm/event.d/${PID}-settings

# Install the govnah executable
mkdir -p /var/usr/sbin/
install -m 755 $APPS/usr/palm/applications/${PID}/bin/${PID} /var/usr/sbin/${PID}

# Install the dbus service
mkdir -p /var/palm/system-services
cp $APPS/usr/palm/applications/${PID}/dbus/${PID}.service /var/palm/system-services/${PID}.service

# Install the ls2 roles
mkdir -p /var/palm/ls2/roles/prv /var/palm/ls2/roles/pub
cp $APPS/usr/palm/applications/${PID}/dbus/${PID}.json /var/palm/ls2/roles/prv/${PID}.json
cp $APPS/usr/palm/applications/${PID}/dbus/${PID}.json /var/palm/ls2/roles/pub/${PID}.json
/usr/bin/ls-control scan-services || true

# Install the upstart script
mkdir -p /var/palm/event.d
cp $APPS/usr/palm/applications/${PID}/upstart/${PID} /var/palm/event.d/${PID}

# Start the service
/sbin/start ${PID}

exit 0
