#!/bin/sh                                                                                       

PID="org.webosinternals.govnah"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Install the upstart script
rm -f /etc/event.d/${PID} /var/palm/event.d/${PID}
if [ -d /var/palm/event.d ] ; then
  cp $APPS/usr/palm/applications/${PID}/upstart/${PID} /var/palm/event.d/${PID}
else
  cp $APPS/usr/palm/applications/${PID}/upstart/${PID} /etc/event.d/${PID}
fi

# Install the dbus service
rm -f /usr/share/dbus-1/system-services/${PID}.service /var/palm/system-services/${PID}.service
if [ -d /var/palm/system-services ] ; then
  cp $APPS/usr/palm/applications/${PID}/dbus/${PID}.service /var/palm/system-services/${PID}.service
else
  cp $APPS/usr/palm/applications/${PID}/dbus/${PID}.service /usr/share/dbus-1/system-services/${PID}.service
fi

# Stop any existing service
/sbin/stop ${PID} || true

# Install the govnah executable
mkdir -p /var/usr/sbin/
rm -f /var/usr/sbin/${PID}
install -m 755 $APPS/usr/palm/applications/${PID}/bin/${PID} /var/usr/sbin/${PID}

# Start the service
/sbin/start ${PID}

# Check the upstart script is installed
[ -f /var/palm/event.d/${PID} ] || [ -f /etc/event.d/${PID} ] || exit 1

# Check the dbus service is installed
[ -f /var/palm/system-services/${PID}.service ] || [ -f /usr/share/dbus-1/system-services/${PID}.service ] || exit 1

exit 0
